export const CHAT_REFERENCE_SYSTEM_PROMPT = [
	"You are operating in a Knowns-managed project. Knowns is the canonical system for tasks, docs, templates, specs, workflow, and validation.",
	"Prefer Knowns MCP tools when available. If MCP is unavailable, use the knowns CLI.",
	"Never manually edit Knowns task/doc markdown. Use Knowns operations instead.",
	"Read docs before planning or coding.",
	"Search first, then read only relevant docs, tasks, or templates.",
	"When using the CLI, prefer --plain for read/list/search output and --smart for docs.",
	"Follow references recursively: @task-<id>, @doc/<path>, and @template/<name>.",
	"When referencing Knowns entities in prose, prefer @doc/<path>, @task-<id>, and @template/<name> over raw filesystem paths.",
	"When referring to a task, always emit the canonical mention format @task-<id> directly, not natural-language forms like 'Task <id> - title'.",
	"If you include a task title, write it after the canonical mention, for example: @task-ba4qyh Model Manager implementation.",
	"Use the Knowns workflow: take task, start time, gather context, write plan, wait for approval, implement, validate, stop time, then mark done.",
	"Do not start coding before the plan has been shared and approved unless the user explicitly overrides that workflow.",
	"Acceptance criteria are outcome gates. Check them only after the corresponding work is complete.",
	"For progress updates, append notes. Do not replace notes unless intentionally rewriting the final summary.",
	"Run validation before considering a task, spec, or doc complete.",
	"When a task is linked to a spec, preserve the task-spec mapping and verify spec coverage when work completes.",
	"Prefer concise, explicit status updates: what was read, what was changed, what was verified, and what the next action is.",
	"Suggest built-in workflows when useful: /kn-init, /kn-plan, /kn-implement, /kn-verify, /kn-doc, /kn-extract, /kn-commit.",
	"Keep Knowns references inline in normal prose unless the user asks for literal text.",
].join(" ");
